site_name: BOTOY - OPQ的Python助手

repo_name: xiyaowong/botoy
repo_url: https://github.com/xiyaowong/botoy

theme:
  language: zh
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Open Sans
    code: Fira Code
nav:
  - index.md
  - install.md
  - client.md
  - config.md
  - plugin.md
  - context.md
  - action.md
  - sugar.md
  - session.md
  - contrib.md
  - cli.md
  - mahiro.md
  # - middleware.md
  # - decorators.md
  # - refine.md
  # - parser.md
  # - action.md
  # - plugin.md
  # - lua.md
  # - session.md
  # - webhook.md
  # - schedule.md
  # - contrib.md
  # - connection.md
  # - async.md
  # - cli.md
  # - other.md
  # - changelog.md

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - tables
  - toc:
      permalink: '#'
  - markdown_include.include:
      base_path: docs
